const THEME_LIMITS = {
  simple: 4,
  medium: 3,
  complex: 2,
};

function hexToRgb(hex) {
  const value = hex.replace('#', '');
  const normalized = value.length === 3
    ? value.split('').map((char) => char + char).join('')
    : value;
  const int = Number.parseInt(normalized, 16);
  return [(int >> 16) & 255, (int >> 8) & 255, int & 255];
}

function rgba(hex, alpha) {
  const [r, g, b] = hexToRgb(hex);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

function navBg(hex, alpha = 0.92) {
  const [r, g, b] = hexToRgb(hex);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

const SOUMYA_GRAPHIC_BASE = '#c770f0';

function hexToHue(hex) {
  const [r, g, b] = hexToRgb(hex).map((value) => value / 255);
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const delta = max - min;
  if (delta === 0) return 0;

  let hue;
  if (max === r) hue = ((g - b) / delta) % 6;
  else if (max === g) hue = (b - r) / delta + 2;
  else hue = (r - g) / delta + 4;

  hue *= 60;
  if (hue < 0) hue += 360;
  return hue;
}

function accentHueRotate(baseHex, targetHex) {
  let delta = hexToHue(targetHex) - hexToHue(baseHex);
  while (delta > 180) delta -= 360;
  while (delta < -180) delta += 360;
  const rounded = Math.round(delta * 10) / 10;
  return `${rounded}deg`;
}

export function createThemeTokens({
  bg,
  surface,
  border,
  text,
  muted,
  accent,
  titleFrom,
  titleTo,
  photoFrom,
  photoTo,
  projectBg,
  gridLine,
  orbSecondary = 'rgba(99, 102, 241, 0.35)',
  accentHover,
}) {
  return {
    '--sawad-bg': bg,
    '--sawad-surface': surface,
    '--sawad-border': border,
    '--sawad-text': text,
    '--sawad-muted': muted,
    '--sawad-orange': accent,
    '--sawad-orange-dim': rgba(accent, 0.15),
    '--sawad-orange-glow': rgba(accent, 0.35),
    '--sawad-nav-bg': navBg(bg),
    '--sawad-title-from': titleFrom,
    '--sawad-title-to': titleTo,
    '--sawad-photo-from': photoFrom,
    '--sawad-photo-to': photoTo,
    '--sawad-project-bg': projectBg,
    '--sawad-grid-line': gridLine,
    '--sawad-orb-secondary': orbSecondary,
    '--sawad-accent-hover': accentHover || accent,
  };
}

export function createVscodeThemeTokens({
  bg,
  surface,
  surface2,
  border,
  text,
  muted,
  accent,
  nameAccent,
  comment,
  keyword,
  idColor,
  stringColor,
  statusBg,
  activityBg,
  cursorDot,
}) {
  const dot = cursorDot || nameAccent;
  return {
    '--vsc-bg': bg,
    '--vsc-surface': surface,
    '--vsc-surface-2': surface2 || surface,
    '--vsc-border': border,
    '--vsc-text': text,
    '--vsc-muted': muted,
    '--vsc-accent': accent,
    '--vsc-accent-dim': rgba(accent, 0.18),
    '--vsc-name-accent': nameAccent,
    '--vsc-comment': comment,
    '--vsc-keyword': keyword,
    '--vsc-id': idColor,
    '--vsc-string': stringColor,
    '--vsc-status-bg': statusBg || accent,
    '--vsc-activity-bg': activityBg || '#333333',
    '--vsc-cursor-dot': dot,
    '--vsc-cursor-ring': rgba(dot, 0.35),
  };
}

export function createDevMinThemeTokens({
  bg,
  surface,
  border,
  text,
  muted,
  accent,
  accentHover,
  sidebarBg,
  cardBg,
  headerBg,
}) {
  return {
    '--devmin-bg': bg,
    '--devmin-surface': surface,
    '--devmin-border': border,
    '--devmin-text': text,
    '--devmin-muted': muted,
    '--devmin-accent': accent,
    '--devmin-accent-dim': rgba(accent, 0.15),
    '--devmin-accent-hover': accentHover || accent,
    '--devmin-sidebar-bg': sidebarBg || surface,
    '--devmin-card-bg': cardBg || surface,
    '--devmin-header-bg': headerBg || navBg(bg),
  };
}

export function createDeveloperClassicThemeTokens({
  bg,
  surface,
  card,
  cardText,
  border,
  text,
  muted,
  accent,
  accentHover,
  navBackground,
  chipBg,
  chipText,
  inputBg,
  inputText,
  timelineLine,
}) {
  const resolvedCardText = cardText || '#272822';
  const resolvedInputText = inputText || resolvedCardText;
  return {
    '--dcls-bg': bg,
    '--dcls-surface': surface,
    '--dcls-card': card,
    '--dcls-card-text': resolvedCardText,
    '--dcls-text': text,
    '--dcls-muted': muted,
    '--dcls-accent': accent,
    '--dcls-accent-hover': accentHover || accent,
    '--dcls-border': border,
    '--dcls-nav-bg': navBackground || navBg(bg),
    '--dcls-hero-overlay': rgba(accent, 0.12),
    '--dcls-chip-bg': chipBg || card,
    '--dcls-chip-text': chipText || resolvedCardText,
    '--dcls-input-bg': inputBg || card,
    '--dcls-input-text': resolvedInputText,
    '--dcls-placeholder': rgba(resolvedInputText, 0.45),
    '--dcls-timeline-line': timelineLine || border,
    '--dcls-project-placeholder': `linear-gradient(135deg, ${rgba(accent, 0.22)}, ${rgba(text, 0.06)})`,
    '--tpl-mobile-panel-bg': surface,
    '--tpl-mobile-muted': muted,
    '--tpl-mobile-accent': accent,
    '--tpl-mobile-accent-dim': rgba(accent, 0.16),
  };
}

export function createCreativeModernThemeTokens({
  bg,
  surface,
  card,
  border,
  text,
  muted,
  accent,
  accentHover,
  secondary,
  headerBg,
  cloud,
}) {
  return {
    '--cmod-bg': bg,
    '--cmod-surface': surface,
    '--cmod-card': card || surface,
    '--cmod-border': border,
    '--cmod-text': text,
    '--cmod-muted': muted,
    '--cmod-accent': accent,
    '--cmod-accent-hover': accentHover || accent,
    '--cmod-accent-dim': rgba(accent, 0.14),
    '--cmod-accent-glow': rgba(accent, 0.22),
    '--cmod-secondary': secondary || accent,
    '--cmod-header-bg': headerBg || navBg(bg, 0.82),
    '--cmod-cloud': cloud || rgba(accent, 0.06),
    '--tpl-mobile-panel-bg': card || surface,
    '--tpl-mobile-muted': muted,
    '--tpl-mobile-accent': accent,
    '--tpl-mobile-accent-dim': rgba(accent, 0.16),
  };
}

export function createSoumyaClassicThemeTokens({
  bg,
  sectionBg,
  purple,
  purpleBright,
  purpleSoft,
  navSticky,
  btn,
  btnHover,
  footerBg,
  preloaderBg,
  surface,
  surfaceDeep,
  mobileNavBg,
  text = '#ffffff',
  muted,
  timeline,
  particleRgb = '255, 255, 255',
  preloaderHue = '0deg',
  illustrationHue,
  illustrationSaturate = '1.05',
}) {
  const accent = purple;
  const bright = purpleBright || purple;
  const soft = purpleSoft || purple;
  const button = btn || accent;
  const buttonHover = btnHover || bright;
  const deep = surfaceDeep || footerBg;
  const panel = surface || deep;
  const graphicHue = accentHueRotate(SOUMYA_GRAPHIC_BASE, accent);

  return {
    '--smcls-bg': bg,
    '--smcls-section-bg': sectionBg,
    '--smcls-purple': accent,
    '--smcls-purple-bright': bright,
    '--smcls-purple-soft': soft,
    '--smcls-purple-cursor': soft,
    '--smcls-text': text,
    '--smcls-muted': muted || rgba(accent, 0.72),
    '--smcls-nav-sticky': navSticky,
    '--smcls-nav-brand-from': button,
    '--smcls-nav-brand-to': bright,
    '--smcls-nav-underline': bright,
    '--smcls-nav-toggle': bright,
    '--smcls-nav-shadow': rgba(accent, 0.17),
    '--smcls-fork-btn': rgba(button, 0.37),
    '--smcls-fork-btn-hover': rgba(buttonHover, 0.53),
    '--smcls-footer-bg': footerBg,
    '--smcls-preloader-bg': preloaderBg || deep,
    '--smcls-btn': button,
    '--smcls-btn-hover': buttonHover,
    '--smcls-card-shadow': rgba(accent, 0.46),
    '--smcls-card-border': rgba(accent, 0.15),
    '--smcls-card-hover-shadow': rgba(accent, 0.56),
    '--smcls-tech-outline': rgba(accent, 0.64),
    '--smcls-tech-shadow': rgba(accent, 0.14),
    '--smcls-tech-hover-outline': rgba(accent, 0.88),
    '--smcls-timeline': timeline || button,
    '--smcls-resume-pill': rgba(button, 0.36),
    '--smcls-social-icon-fg': button,
    '--smcls-social-ring': rgba(button, 0.85),
    '--smcls-social-glow': rgba(bright, 0.55),
    '--smcls-social-hover-fg': bright,
    '--smcls-project-thumb': `linear-gradient(145deg, ${rgba(button, 0.45)}, ${deep})`,
    '--smcls-laptop-bg': `linear-gradient(160deg, ${panel}, ${deep})`,
    '--smcls-laptop-border': rgba(accent, 0.35),
    '--smcls-laptop-screen': `linear-gradient(135deg, ${rgba(accent, 0.25)}, ${rgba(button, 0.15)})`,
    '--smcls-laptop-screen-border': rgba(accent, 0.2),
    '--smcls-laptop-base': deep,
    '--smcls-mobile-nav-bg': mobileNavBg || deep,
    '--smcls-particle-rgb': particleRgb,
    '--smcls-timeline-dot': text,
    '--smcls-preloader-hue': preloaderHue ?? graphicHue,
    '--smcls-illustration-hue': illustrationHue ?? graphicHue,
    '--smcls-illustration-saturate': illustrationSaturate,
  };
}

export function createAuroraFluxThemeTokens({
  bg,
  surface,
  surfaceHover,
  border,
  text,
  muted,
  accent,
  accent2,
  accentGlow,
  dockBg,
  aurora1,
  aurora2,
  aurora3,
  gridLine,
}) {
  const secondary = accent2 || accent;
  const panel = dockBg || 'rgba(12, 12, 18, 0.72)';

  return {
    '--aflux-bg': bg,
    '--aflux-surface': surface,
    '--aflux-surface-hover': surfaceHover || surface,
    '--aflux-border': border,
    '--aflux-text': text,
    '--aflux-muted': muted,
    '--aflux-accent': accent,
    '--aflux-accent-2': secondary,
    '--aflux-accent-glow': accentGlow || rgba(accent, 0.45),
    '--aflux-dock-bg': panel,
    '--aflux-aurora-1': aurora1 || rgba(accent, 0.35),
    '--aflux-aurora-2': aurora2 || rgba(secondary, 0.28),
    '--aflux-aurora-3': aurora3 || rgba(accent, 0.22),
    '--aflux-grid-line': gridLine || border,
    '--tpl-mobile-border': border,
    '--tpl-mobile-surface': surface,
    '--tpl-mobile-surface-hover': surfaceHover || surface,
    '--tpl-mobile-panel-bg': panel,
    '--tpl-mobile-muted': muted,
    '--tpl-mobile-accent': accent,
    '--tpl-mobile-accent-dim': rgba(accent, 0.16),
  };
}

export function createLumenBloomThemeTokens({
  bg,
  surface,
  surfaceSoft,
  border,
  text,
  muted,
  accent,
  accent2,
  accentSoft,
  blob1,
  blob2,
  blob3,
  ribbonBg,
  shadow,
  shadowDeep,
}) {
  const secondary = accent2 || accent;

  return {
    '--lbloom-bg': bg,
    '--lbloom-surface': surface,
    '--lbloom-surface-soft': surfaceSoft || surface,
    '--lbloom-border': border,
    '--lbloom-text': text,
    '--lbloom-muted': muted,
    '--lbloom-accent': accent,
    '--lbloom-accent-2': secondary,
    '--lbloom-accent-soft': accentSoft || rgba(accent, 0.12),
    '--lbloom-shadow': shadow || rgba(text, 0.08),
    '--lbloom-shadow-deep': shadowDeep || rgba(text, 0.14),
    '--lbloom-blob-1': blob1 || rgba(accent, 0.22),
    '--lbloom-blob-2': blob2 || rgba(secondary, 0.2),
    '--lbloom-blob-3': blob3 || rgba(accent, 0.15),
    '--lbloom-ribbon-bg': ribbonBg || 'rgba(255, 255, 255, 0.82)',
    '--tpl-mobile-border': border,
    '--tpl-mobile-surface': surface,
    '--tpl-mobile-surface-hover': surfaceSoft || surface,
    '--tpl-mobile-panel-bg': surface,
    '--tpl-mobile-muted': muted,
    '--tpl-mobile-accent': accent,
    '--tpl-mobile-accent-dim': accentSoft || rgba(accent, 0.12),
  };
}

export function createMidnightGoldThemeTokens({
  bg,
  surface,
  surfaceElevated,
  border,
  borderSoft,
  text,
  muted,
  gold,
  goldLight,
  goldGlow,
  vignette,
}) {
  return {
    '--mgold-bg': bg,
    '--mgold-surface': surface,
    '--mgold-surface-elevated': surfaceElevated || surface,
    '--mgold-border': border,
    '--mgold-border-soft': borderSoft || border,
    '--mgold-text': text,
    '--mgold-muted': muted,
    '--mgold-gold': gold,
    '--mgold-gold-light': goldLight || gold,
    '--mgold-gold-glow': goldGlow || rgba(gold, 0.35),
    '--mgold-gradient': `linear-gradient(135deg, ${goldLight || gold}, ${gold})`,
    '--mgold-vignette': vignette || `radial-gradient(ellipse 80% 60% at 50% 0%, ${rgba(gold, 0.08)}, transparent 70%)`,
    '--tpl-mobile-border': borderSoft || border,
    '--tpl-mobile-surface': surface,
    '--tpl-mobile-surface-hover': surfaceElevated || surface,
    '--tpl-mobile-panel-bg': surface,
    '--tpl-mobile-muted': muted,
    '--tpl-mobile-accent': gold,
    '--tpl-mobile-accent-dim': rgba(gold, 0.14),
  };
}

export function createPrismDriftThemeTokens({
  bg,
  surface,
  surfaceSoft,
  border,
  text,
  muted,
  accent,
  accent2,
  accent3,
  meshA,
  meshB,
  glow,
}) {
  return {
    '--pdrift-bg': bg,
    '--pdrift-surface': surface,
    '--pdrift-surface-soft': surfaceSoft || surface,
    '--pdrift-border': border,
    '--pdrift-text': text,
    '--pdrift-muted': muted,
    '--pdrift-accent': accent,
    '--pdrift-accent-2': accent2 || accent,
    '--pdrift-accent-3': accent3 || accent2 || accent,
    '--pdrift-gradient': `linear-gradient(125deg, ${accent}, ${accent2 || accent}, ${accent3 || accent2 || accent})`,
    '--pdrift-mesh-a': meshA || rgba(accent, 0.14),
    '--pdrift-mesh-b': meshB || rgba(accent2 || accent, 0.12),
    '--pdrift-glow': glow || rgba(accent, 0.35),
    '--tpl-mobile-border': border,
    '--tpl-mobile-surface': surface,
    '--tpl-mobile-surface-hover': surfaceSoft || surface,
    '--tpl-mobile-panel-bg': surface,
    '--tpl-mobile-muted': muted,
    '--tpl-mobile-accent': accent,
    '--tpl-mobile-accent-dim': rgba(accent, 0.14),
  };
}

export const TEMPLATE_THEME_REGISTRY = {
  'dev-minimal': {
    complexity: 'medium',
    maxThemes: 4,
    themes: [
      {
        id: 'dark-purple',
        name: 'Dark Purple',
        swatch: ['#09090b', '#8b5cf6'],
        vars: createDevMinThemeTokens({
          bg: '#09090b',
          surface: '#18181b',
          border: 'rgba(255, 255, 255, 0.1)',
          text: '#fafafa',
          muted: '#a1a1aa',
          accent: '#8b5cf6',
          accentHover: '#a78bfa',
          sidebarBg: '#18181b',
          cardBg: '#1c1c20',
        }),
      },
      {
        id: 'dark-slate',
        name: 'Dark Slate',
        swatch: ['#0f172a', '#38bdf8'],
        vars: createDevMinThemeTokens({
          bg: '#0f172a',
          surface: '#1e293b',
          border: 'rgba(148, 163, 184, 0.2)',
          text: '#f8fafc',
          muted: '#94a3b8',
          accent: '#38bdf8',
          accentHover: '#7dd3fc',
          sidebarBg: '#1e293b',
          cardBg: '#1e293b',
        }),
      },
      {
        id: 'dark-emerald',
        name: 'Dark Emerald',
        swatch: ['#022c22', '#34d399'],
        vars: createDevMinThemeTokens({
          bg: '#022c22',
          surface: '#064e3b',
          border: 'rgba(52, 211, 153, 0.15)',
          text: '#ecfdf5',
          muted: '#6ee7b7',
          accent: '#34d399',
          accentHover: '#6ee7b7',
          sidebarBg: '#064e3b',
          cardBg: '#065f46',
        }),
      },
      {
        id: 'light-minimal',
        name: 'Light Minimal',
        swatch: ['#ffffff', '#6366f1'],
        vars: createDevMinThemeTokens({
          bg: '#ffffff',
          surface: '#f4f4f5',
          border: 'rgba(0, 0, 0, 0.08)',
          text: '#18181b',
          muted: '#71717a',
          accent: '#6366f1',
          accentHover: '#818cf8',
          sidebarBg: '#fafafa',
          cardBg: '#f4f4f5',
          headerBg: 'rgba(255, 255, 255, 0.92)',
        }),
      },
    ],
  },
  'dark-orange-pro': {
    complexity: 'medium',
    maxThemes: 4,
    themes: [
      {
        id: 'black-orange',
        name: 'Black Orange',
        swatch: ['#0a0a0a', '#ff6b2c'],
        vars: createThemeTokens({
          bg: '#0a0a0a',
          surface: '#141414',
          border: '#262626',
          text: '#ffffff',
          muted: '#9ca3af',
          accent: '#ff6b2c',
          accentHover: '#ff7f45',
          titleFrom: '#ffffff',
          titleTo: '#d4d4d4',
          photoFrom: '#1a1a1a',
          photoTo: '#0f0f0f',
          projectBg: 'linear-gradient(145deg, #1a1a1a 0%, #2d1810 50%, #1a1a1a 100%)',
          gridLine: 'rgba(255, 255, 255, 0.03)',
        }),
      },
      {
        id: 'white-orange',
        name: 'White Orange',
        swatch: ['#fafafa', '#ff6b2c'],
        vars: createThemeTokens({
          bg: '#fafafa',
          surface: '#ffffff',
          border: '#e5e7eb',
          text: '#0a0a0a',
          muted: '#6b7280',
          accent: '#ff6b2c',
          accentHover: '#ff7f45',
          titleFrom: '#0a0a0a',
          titleTo: '#525252',
          photoFrom: '#f3f4f6',
          photoTo: '#e5e7eb',
          projectBg: 'linear-gradient(145deg, #f3f4f6 0%, #ffedd5 50%, #f3f4f6 100%)',
          gridLine: 'rgba(0, 0, 0, 0.05)',
          orbSecondary: 'rgba(255, 107, 44, 0.2)',
        }),
      },
      {
        id: 'black-neon-green',
        name: 'Black Neon',
        swatch: ['#0a0a0a', '#00ff88'],
        vars: createThemeTokens({
          bg: '#0a0a0a',
          surface: '#0f1410',
          border: '#1f2e24',
          text: '#ffffff',
          muted: '#94a3b8',
          accent: '#00ff88',
          accentHover: '#33ffaa',
          titleFrom: '#ffffff',
          titleTo: '#86efac',
          photoFrom: '#0f1a14',
          photoTo: '#0a0f0c',
          projectBg: 'linear-gradient(145deg, #0f1a14 0%, #0d2818 50%, #0f1a14 100%)',
          gridLine: 'rgba(0, 255, 136, 0.06)',
          orbSecondary: 'rgba(0, 255, 136, 0.25)',
        }),
      },
      {
        id: 'black-purple',
        name: 'Black Purple',
        swatch: ['#0a0a0a', '#a855f7'],
        vars: createThemeTokens({
          bg: '#0a0a0a',
          surface: '#12101a',
          border: '#2a2438',
          text: '#ffffff',
          muted: '#a1a1aa',
          accent: '#a855f7',
          accentHover: '#c084fc',
          titleFrom: '#ffffff',
          titleTo: '#d8b4fe',
          photoFrom: '#1a1424',
          photoTo: '#0f0a14',
          projectBg: 'linear-gradient(145deg, #1a1424 0%, #2e1065 50%, #1a1424 100%)',
          gridLine: 'rgba(168, 85, 247, 0.06)',
          orbSecondary: 'rgba(168, 85, 247, 0.28)',
        }),
      },
    ],
  },
  'vscode-studio': {
    complexity: 'medium',
    maxThemes: 4,
    themes: [
      {
        id: 'aahana-dark',
        name: 'Aahana Dark',
        swatch: ['#1e1e1e', '#c586c0'],
        vars: createVscodeThemeTokens({
          bg: '#1e1e1e',
          surface: '#252526',
          surface2: '#2d2d2d',
          border: '#3c3c3c',
          text: '#cccccc',
          muted: '#858585',
          accent: '#007acc',
          nameAccent: '#c586c0',
          comment: '#6a9955',
          keyword: '#569cd6',
          idColor: '#9cdcfe',
          stringColor: '#ce9178',
          statusBg: '#007acc',
        }),
      },
      {
        id: 'vscode-classic',
        name: 'VS Code Classic',
        swatch: ['#1e1e1e', '#007acc'],
        vars: createVscodeThemeTokens({
          bg: '#1e1e1e',
          surface: '#252526',
          surface2: '#2d2d2d',
          border: '#3c3c3c',
          text: '#d4d4d4',
          muted: '#808080',
          accent: '#007acc',
          nameAccent: '#4fc1ff',
          comment: '#6a9955',
          keyword: '#569cd6',
          idColor: '#9cdcfe',
          stringColor: '#ce9178',
          statusBg: '#007acc',
        }),
      },
      {
        id: 'monokai-night',
        name: 'Monokai Night',
        swatch: ['#272822', '#a6e22e'],
        vars: createVscodeThemeTokens({
          bg: '#272822',
          surface: '#2f302a',
          surface2: '#383830',
          border: '#49483e',
          text: '#f8f8f2',
          muted: '#a59f85',
          accent: '#a6e22e',
          nameAccent: '#f92672',
          comment: '#75715e',
          keyword: '#f92672',
          idColor: '#a6e22e',
          stringColor: '#e6db74',
          statusBg: '#49483e',
          activityBg: '#1e1f1c',
          cursorDot: '#f92672',
        }),
      },
      {
        id: 'github-light',
        name: 'GitHub Light',
        swatch: ['#ffffff', '#0969da'],
        vars: createVscodeThemeTokens({
          bg: '#ffffff',
          surface: '#f6f8fa',
          surface2: '#eaeef2',
          border: '#d0d7de',
          text: '#24292f',
          muted: '#57606a',
          accent: '#0969da',
          nameAccent: '#8250df',
          comment: '#6e7781',
          keyword: '#cf222e',
          idColor: '#0550ae',
          stringColor: '#0a3069',
          statusBg: '#0969da',
          activityBg: '#f6f8fa',
          cursorDot: '#8250df',
        }),
      },
    ],
  },
  'creative-modern': {
    complexity: 'medium',
    maxThemes: 4,
    themes: [
      {
        id: 'light-breeze',
        name: 'Light Breeze',
        swatch: ['#f8fafc', '#0891b2'],
        vars: createCreativeModernThemeTokens({
          bg: '#f8fafc',
          surface: '#ffffff',
          card: '#ffffff',
          border: 'rgba(15, 23, 42, 0.08)',
          text: '#0f172a',
          muted: '#64748b',
          accent: '#0891b2',
          accentHover: '#06b6d4',
          secondary: '#6366f1',
          headerBg: 'rgba(248, 250, 252, 0.88)',
          cloud: 'rgba(8, 145, 178, 0.06)',
        }),
      },
      {
        id: 'midnight-cyan',
        name: 'Midnight Cyan',
        swatch: ['#050508', '#06b6d4'],
        vars: createCreativeModernThemeTokens({
          bg: '#050508',
          surface: '#0f1018',
          card: '#141622',
          border: 'rgba(255, 255, 255, 0.08)',
          text: '#f8fafc',
          muted: '#94a3b8',
          accent: '#06b6d4',
          accentHover: '#22d3ee',
          secondary: '#8b5cf6',
        }),
      },
      {
        id: 'violet-dream',
        name: 'Violet Dream',
        swatch: ['#0a0612', '#a855f7'],
        vars: createCreativeModernThemeTokens({
          bg: '#0a0612',
          surface: '#130d1f',
          card: '#1a1228',
          border: 'rgba(168, 85, 247, 0.12)',
          text: '#faf5ff',
          muted: '#c4b5fd',
          accent: '#a855f7',
          accentHover: '#c084fc',
          secondary: '#ec4899',
          cloud: 'rgba(168, 85, 247, 0.08)',
        }),
      },
      {
        id: 'sunset-glow',
        name: 'Sunset Glow',
        swatch: ['#0c0a09', '#f97316'],
        vars: createCreativeModernThemeTokens({
          bg: '#0c0a09',
          surface: '#171311',
          card: '#1f1914',
          border: 'rgba(249, 115, 22, 0.12)',
          text: '#fff7ed',
          muted: '#fdba74',
          accent: '#f97316',
          accentHover: '#fb923c',
          secondary: '#facc15',
          cloud: 'rgba(249, 115, 22, 0.07)',
        }),
      },
    ],
  },
  'developer-classic': {
    complexity: 'medium',
    maxThemes: 4,
    themes: [
      {
        id: 'classic-dark',
        name: 'Classic Dark',
        swatch: ['#0d1116', '#5000ca'],
        vars: createDeveloperClassicThemeTokens({
          bg: '#0d1116',
          surface: '#141a22',
          card: '#ffffff',
          border: 'rgba(255, 255, 255, 0.08)',
          text: '#ffffff',
          muted: '#a8b0bc',
          accent: '#5000ca',
          accentHover: '#6b1fe6',
        }),
      },
      {
        id: 'classic-light',
        name: 'Classic Light',
        swatch: ['#f8f9fa', '#5000ca'],
        vars: createDeveloperClassicThemeTokens({
          bg: '#f8f9fa',
          surface: '#ffffff',
          card: '#ffffff',
          cardText: '#0d1116',
          border: 'rgba(13, 17, 22, 0.08)',
          text: '#0d1116',
          muted: '#5c6672',
          accent: '#5000ca',
          navBackground: 'rgba(248, 249, 250, 0.92)',
          timelineLine: 'rgba(13, 17, 22, 0.08)',
        }),
      },
      {
        id: 'midnight-blue',
        name: 'Midnight Blue',
        swatch: ['#08111f', '#3b82f6'],
        vars: createDeveloperClassicThemeTokens({
          bg: '#08111f',
          surface: '#0f1b2d',
          card: '#ffffff',
          border: 'rgba(255, 255, 255, 0.08)',
          text: '#f8fafc',
          muted: '#94a3b8',
          accent: '#3b82f6',
          accentHover: '#60a5fa',
        }),
      },
      {
        id: 'violet-night',
        name: 'Violet Night',
        swatch: ['#100818', '#a855f7'],
        vars: createDeveloperClassicThemeTokens({
          bg: '#100818',
          surface: '#1a1024',
          card: '#ffffff',
          border: 'rgba(168, 85, 247, 0.12)',
          text: '#faf5ff',
          muted: '#c4b5fd',
          accent: '#a855f7',
          accentHover: '#c084fc',
        }),
      },
    ],
  },
  'soumya-classic': {
    complexity: 'medium',
    maxThemes: 4,
    themes: [
      {
        id: 'purple-night',
        name: 'Purple Night',
        swatch: ['#1b1429', '#c770f0'],
        vars: createSoumyaClassicThemeTokens({
          bg: 'linear-gradient(to left, rgb(27 20 41), rgb(20 15 35))',
          sectionBg: 'linear-gradient(to bottom left, rgba(17, 16, 16, 0.582), rgba(12, 8, 24, 0.904))',
          purple: '#c770f0',
          purpleBright: '#cd5ff8',
          purpleSoft: '#be6adf',
          navSticky: '#1b1a2ea9',
          btn: '#623686',
          btnHover: '#6d20c5',
          footerBg: 'rgb(10, 4, 22)',
          preloaderBg: '#0c0513',
          surface: '#2a1f42',
          surfaceDeep: '#120a22',
          mobileNavBg: '#181a27',
          muted: '#a588c0',
          timeline: '#8a49a8',
        }),
      },
      {
        id: 'violet-ember',
        name: 'Violet Ember',
        swatch: ['#12081c', '#d946ef'],
        vars: createSoumyaClassicThemeTokens({
          bg: 'linear-gradient(to left, rgb(24 10 38), rgb(16 8 28))',
          sectionBg: 'linear-gradient(to bottom left, rgba(28, 8, 36, 0.62), rgba(14, 4, 22, 0.92))',
          purple: '#d946ef',
          purpleBright: '#e879f9',
          purpleSoft: '#c026d3',
          navSticky: '#22102ea9',
          btn: '#7e22ce',
          btnHover: '#9333ea',
          footerBg: 'rgb(12, 4, 20)',
          preloaderBg: '#0a0312',
          surface: '#32124a',
          surfaceDeep: '#14081e',
          mobileNavBg: '#1c0e28',
          muted: '#e9a8f5',
          timeline: '#a855f7',
        }),
      },
      {
        id: 'indigo-haze',
        name: 'Indigo Haze',
        swatch: ['#0f172a', '#818cf8'],
        vars: createSoumyaClassicThemeTokens({
          bg: 'linear-gradient(to left, rgb(15 23 42), rgb(10 16 30))',
          sectionBg: 'linear-gradient(to bottom left, rgba(12, 18, 36, 0.62), rgba(8, 12, 26, 0.92))',
          purple: '#818cf8',
          purpleBright: '#a5b4fc',
          purpleSoft: '#6366f1',
          navSticky: '#1e293ba9',
          btn: '#4338ca',
          btnHover: '#4f46e5',
          footerBg: 'rgb(8, 12, 24)',
          preloaderBg: '#060a14',
          surface: '#1e2a44',
          surfaceDeep: '#0c1220',
          mobileNavBg: '#141c2e',
          muted: '#a5b4fc',
          timeline: '#6366f1',
        }),
      },
      {
        id: 'magenta-dusk',
        name: 'Magenta Dusk',
        swatch: ['#1a0a14', '#f472b6'],
        vars: createSoumyaClassicThemeTokens({
          bg: 'linear-gradient(to left, rgb(26 10 20), rgb(18 8 14))',
          sectionBg: 'linear-gradient(to bottom left, rgba(30, 8, 22, 0.62), rgba(16, 4, 12, 0.92))',
          purple: '#f472b6',
          purpleBright: '#f9a8d4',
          purpleSoft: '#ec4899',
          navSticky: '#2a1220a9',
          btn: '#9d174d',
          btnHover: '#be185d',
          footerBg: 'rgb(14, 4, 10)',
          preloaderBg: '#0c0308',
          surface: '#3a1428',
          surfaceDeep: '#180810',
          mobileNavBg: '#220e18',
          muted: '#f9a8d4',
          timeline: '#db2777',
        }),
      },
    ],
  },
  'aurora-flux': {
    complexity: 'medium',
    maxThemes: 4,
    themes: [
      {
        id: 'cosmic-cyan',
        name: 'Cosmic Cyan',
        swatch: ['#050508', '#22d3ee'],
        vars: createAuroraFluxThemeTokens({
          bg: '#050508',
          surface: 'rgba(255, 255, 255, 0.04)',
          surfaceHover: 'rgba(255, 255, 255, 0.07)',
          border: 'rgba(255, 255, 255, 0.1)',
          text: '#f4f4f5',
          muted: '#a1a1aa',
          accent: '#22d3ee',
          accent2: '#e879f9',
          aurora3: 'rgba(99, 102, 241, 0.22)',
        }),
      },
      {
        id: 'solar-flare',
        name: 'Solar Flare',
        swatch: ['#0c0a09', '#f97316'],
        vars: createAuroraFluxThemeTokens({
          bg: '#0c0a09',
          surface: 'rgba(255, 255, 255, 0.05)',
          surfaceHover: 'rgba(255, 255, 255, 0.08)',
          border: 'rgba(249, 115, 22, 0.15)',
          text: '#fff7ed',
          muted: '#fdba74',
          accent: '#f97316',
          accent2: '#facc15',
          aurora3: 'rgba(239, 68, 68, 0.2)',
        }),
      },
      {
        id: 'neon-forest',
        name: 'Neon Forest',
        swatch: ['#04120c', '#34d399'],
        vars: createAuroraFluxThemeTokens({
          bg: '#04120c',
          surface: 'rgba(255, 255, 255, 0.04)',
          surfaceHover: 'rgba(255, 255, 255, 0.07)',
          border: 'rgba(52, 211, 153, 0.14)',
          text: '#ecfdf5',
          muted: '#6ee7b7',
          accent: '#34d399',
          accent2: '#22c55e',
          aurora3: 'rgba(16, 185, 129, 0.18)',
        }),
      },
      {
        id: 'royal-void',
        name: 'Royal Void',
        swatch: ['#0a0614', '#a78bfa'],
        vars: createAuroraFluxThemeTokens({
          bg: '#0a0614',
          surface: 'rgba(255, 255, 255, 0.04)',
          surfaceHover: 'rgba(255, 255, 255, 0.07)',
          border: 'rgba(167, 139, 250, 0.14)',
          text: '#faf5ff',
          muted: '#c4b5fd',
          accent: '#a78bfa',
          accent2: '#c084fc',
          aurora3: 'rgba(139, 92, 246, 0.22)',
        }),
      },
    ],
  },
  'lumen-bloom': {
    complexity: 'medium',
    maxThemes: 4,
    themes: [
      {
        id: 'morning-linen',
        name: 'Morning Linen',
        swatch: ['#faf7f2', '#e07a5f'],
        vars: createLumenBloomThemeTokens({
          bg: '#faf7f2',
          surface: '#ffffff',
          surfaceSoft: '#f3efe8',
          border: 'rgba(45, 49, 66, 0.1)',
          text: '#2d3142',
          muted: '#6d7280',
          accent: '#e07a5f',
          accent2: '#81b29a',
        }),
      },
      {
        id: 'cloud-slate',
        name: 'Cloud Slate',
        swatch: ['#f4f6f8', '#4a90d9'],
        vars: createLumenBloomThemeTokens({
          bg: '#f4f6f8',
          surface: '#ffffff',
          surfaceSoft: '#e8edf2',
          border: 'rgba(45, 55, 72, 0.1)',
          text: '#2d3748',
          muted: '#718096',
          accent: '#4a90d9',
          accent2: '#9b8fd9',
          blob3: 'rgba(155, 143, 217, 0.22)',
        }),
      },
      {
        id: 'blush-petal',
        name: 'Blush Petal',
        swatch: ['#fff5f5', '#d9738c'],
        vars: createLumenBloomThemeTokens({
          bg: '#fff5f5',
          surface: '#ffffff',
          surfaceSoft: '#fce8ec',
          border: 'rgba(120, 53, 68, 0.1)',
          text: '#3d2c32',
          muted: '#8b6b72',
          accent: '#d9738c',
          accent2: '#f4a261',
          blob2: 'rgba(244, 162, 97, 0.22)',
        }),
      },
      {
        id: 'mint-studio',
        name: 'Mint Studio',
        swatch: ['#f2faf6', '#2a9d8f'],
        vars: createLumenBloomThemeTokens({
          bg: '#f2faf6',
          surface: '#ffffff',
          surfaceSoft: '#e6f5ef',
          border: 'rgba(26, 86, 74, 0.1)',
          text: '#1f3d36',
          muted: '#5c7a72',
          accent: '#2a9d8f',
          accent2: '#a7c957',
          blob1: 'rgba(42, 157, 143, 0.2)',
        }),
      },
    ],
  },
  'midnight-gold': {
    complexity: 'medium',
    maxThemes: 4,
    themes: [
      {
        id: 'champagne-vault',
        name: 'Champagne Vault',
        swatch: ['#08090d', '#c9a44c'],
        vars: createMidnightGoldThemeTokens({
          bg: '#08090d',
          surface: '#11141c',
          surfaceElevated: '#181c26',
          border: 'rgba(201, 164, 76, 0.18)',
          borderSoft: 'rgba(255, 255, 255, 0.06)',
          text: '#f7f4ee',
          muted: '#9a958c',
          gold: '#c9a44c',
          goldLight: '#e8d4a8',
        }),
      },
      {
        id: 'rose-aureate',
        name: 'Rose Aureate',
        swatch: ['#120a0e', '#d4a574'],
        vars: createMidnightGoldThemeTokens({
          bg: '#120a0e',
          surface: '#1a1018',
          surfaceElevated: '#241420',
          border: 'rgba(212, 165, 116, 0.2)',
          borderSoft: 'rgba(255, 255, 255, 0.05)',
          text: '#faf5f2',
          muted: '#b09a8c',
          gold: '#d4a574',
          goldLight: '#f0d4b8',
          goldGlow: 'rgba(212, 165, 116, 0.38)',
        }),
      },
      {
        id: 'arctic-platinum',
        name: 'Arctic Platinum',
        swatch: ['#0a1018', '#b8c4d4'],
        vars: createMidnightGoldThemeTokens({
          bg: '#0a1018',
          surface: '#121a24',
          surfaceElevated: '#1a2430',
          border: 'rgba(184, 196, 212, 0.2)',
          borderSoft: 'rgba(255, 255, 255, 0.06)',
          text: '#f0f4f8',
          muted: '#8a96a8',
          gold: '#b8c4d4',
          goldLight: '#dce4ee',
          goldGlow: 'rgba(184, 196, 212, 0.32)',
          vignette: 'radial-gradient(ellipse 80% 60% at 50% 0%, rgba(184, 196, 212, 0.1), transparent 70%)',
        }),
      },
      {
        id: 'emerald-estate',
        name: 'Emerald Estate',
        swatch: ['#081210', '#6ab89a'],
        vars: createMidnightGoldThemeTokens({
          bg: '#081210',
          surface: '#0f1a16',
          surfaceElevated: '#152420',
          border: 'rgba(106, 184, 154, 0.22)',
          borderSoft: 'rgba(255, 255, 255, 0.05)',
          text: '#eef6f2',
          muted: '#8aa89c',
          gold: '#6ab89a',
          goldLight: '#b8d4a0',
          goldGlow: 'rgba(106, 184, 154, 0.35)',
          vignette: 'radial-gradient(ellipse 80% 60% at 50% 0%, rgba(106, 184, 154, 0.1), transparent 70%)',
        }),
      },
    ],
  },
  'prism-drift': {
    complexity: 'medium',
    maxThemes: 4,
    themes: [
      {
        id: 'electric-void',
        name: 'Electric Void',
        swatch: ['#0e0e14', '#ff3cac'],
        vars: createPrismDriftThemeTokens({
          bg: '#0e0e14',
          surface: '#161622',
          surfaceSoft: '#1e1e2c',
          border: 'rgba(255, 255, 255, 0.08)',
          text: '#f2f2f7',
          muted: '#8b8b9e',
          accent: '#ff3cac',
          accent2: '#4facfe',
          accent3: '#78ffd6',
        }),
      },
      {
        id: 'solar-rift',
        name: 'Solar Rift',
        swatch: ['#120c08', '#ff6b35'],
        vars: createPrismDriftThemeTokens({
          bg: '#120c08',
          surface: '#1c1410',
          surfaceSoft: '#261c16',
          border: 'rgba(255, 255, 255, 0.08)',
          text: '#fff5f0',
          muted: '#a89488',
          accent: '#ff6b35',
          accent2: '#ffc53d',
          accent3: '#ff8fab',
          meshA: 'rgba(255, 107, 53, 0.16)',
          meshB: 'rgba(255, 197, 61, 0.12)',
          glow: 'rgba(255, 107, 53, 0.38)',
        }),
      },
      {
        id: 'toxic-lime',
        name: 'Toxic Lime',
        swatch: ['#0a1008', '#b8ff3c'],
        vars: createPrismDriftThemeTokens({
          bg: '#0a1008',
          surface: '#121a10',
          surfaceSoft: '#1a2416',
          border: 'rgba(184, 255, 60, 0.1)',
          text: '#f0ffe8',
          muted: '#8aa878',
          accent: '#b8ff3c',
          accent2: '#3cff8f',
          accent3: '#e8ff78',
          meshA: 'rgba(184, 255, 60, 0.14)',
          meshB: 'rgba(60, 255, 143, 0.1)',
          glow: 'rgba(184, 255, 60, 0.32)',
        }),
      },
      {
        id: 'violet-haze',
        name: 'Violet Haze',
        swatch: ['#100818', '#c084fc'],
        vars: createPrismDriftThemeTokens({
          bg: '#100818',
          surface: '#181024',
          surfaceSoft: '#201830',
          border: 'rgba(192, 132, 252, 0.12)',
          text: '#faf5ff',
          muted: '#a78bb8',
          accent: '#c084fc',
          accent2: '#818cf8',
          accent3: '#f0abfc',
          meshA: 'rgba(192, 132, 252, 0.15)',
          meshB: 'rgba(129, 140, 248, 0.12)',
          glow: 'rgba(192, 132, 252, 0.35)',
        }),
      },
    ],
  },
  'ai-dynamic': {
    complexity: 'medium',
    maxThemes: 2,
    themes: [
      {
        id: 'ai-dark',
        name: 'AI Dark',
        swatch: ['#070b16', '#6366f1'],
        vars: {
          '--bg': '#070b16',
          '--text': '#f8fafc',
          '--accent': '#6366f1',
        },
      },
      {
        id: 'ai-light',
        name: 'AI Light',
        swatch: ['#f6f8fc', '#4f46e5'],
        vars: {
          '--bg': '#f6f8fc',
          '--text': '#0f172a',
          '--accent': '#4f46e5',
        },
      },
    ],
  },
};

export function getThemesForTemplate(templateId) {
  const entry = TEMPLATE_THEME_REGISTRY[templateId];
  if (!entry) return [];
  const limit = entry.maxThemes ?? THEME_LIMITS[entry.complexity] ?? 4;
  return entry.themes.slice(0, Math.min(entry.themes.length, limit));
}

export function getDefaultThemeId(templateId) {
  const themes = getThemesForTemplate(templateId);
  return themes[0]?.id || null;
}

export function getThemeById(templateId, themeId) {
  return getThemesForTemplate(templateId).find((theme) => theme.id === themeId) || null;
}

export function getThemeLimit(complexity) {
  return THEME_LIMITS[complexity] ?? 4;
}
